// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_prize_oriented = "CgkIz7ix1aMCEAIQBw"; // <GPGSID>
        public const string achievement_newbie = "CgkIz7ix1aMCEAIQAQ"; // <GPGSID>
        public const string achievement_challenger = "CgkIz7ix1aMCEAIQCA"; // <GPGSID>
        public const string achievement_was_scrapped = "CgkIz7ix1aMCEAIQAg"; // <GPGSID>
        public const string achievement_millionaire = "CgkIz7ix1aMCEAIQBA"; // <GPGSID>
        public const string achievement_investor = "CgkIz7ix1aMCEAIQBg"; // <GPGSID>
        public const string achievement_slime_defeat = "CgkIz7ix1aMCEAIQCQ"; // <GPGSID>
        public const string achievement_collector = "CgkIz7ix1aMCEAIQAw"; // <GPGSID>
        public const string achievement_jeweler = "CgkIz7ix1aMCEAIQBQ"; // <GPGSID>
        public const string achievement_no_stranger_to_fighting = "CgkIz7ix1aMCEAIQCg"; // <GPGSID>

}

